apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: NAME_TO_REPLACE
  region: REGION_TO_REPLACE
  version: "1.22"
iam:
  withOIDC: true
managedNodeGroups:
  - name: default-ng
    minSize: 1
    maxSize: 5
    desiredCapacity: 2
    labels: {role: mngworker}
    iam:
      withAddonPolicies:
        imageBuilder: true
        autoScaler: true
        externalDNS: true
        certManager: true
        ebs: true
        albIngress: true
        xRay: true
        cloudWatch: true
        appMesh: true
cloudWatch:
  clusterLogging:
    enableTypes: ["*"]